apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:10.1
        env:
        - name: POSTGRES_USER
          value: demo
        - name: POSTGRES_PASSWORD
          value: example
        ports:
        - containerPort: 5432
