services:
  db:
    image: postgres:10.1
    restart: always
    environment: 
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: example

    ports:
      - "5432:5432"

  app:
    image: javaapp-app
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
